name: Birthdays Reminder
on:
  schedule:
    - cron: '0 06 * * *'  # Schedule the job to run once a day at 06:00 AM (UTC) / 08:00 SAST
  workflow_dispatch:  # Allows manual triggering

jobs:
  run_stock_price_forecasts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install requests datetime

    - name: Run the script
      run: python Birthdays_Reminder/main.py
