name: Tracks Latest and Trending Data Science Articles
on:
  schedule:
    - cron: '0 12 * * *'  # Schedule the job to run once a day at 12:00 PM (UTC) / 14:00 SAST
  workflow_dispatch:  # Allows manual triggering

env:
  PYTHON_VERSION: 3.9  

jobs:
  track_articles:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify installed packages
      run: pip list

    - name: Run the script
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        LIMIT_ARTICLES: ${{ secrets.LIMIT_ARTICLES }}
      run: python Latest_DS_trends/pipeline.py
