name: Price Tracker

on:
  schedule:
    - cron: '0 04 * * *'  # Schedule the job to run once a day at 04 AM (UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  track_prices:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml  

    - name: Run the script
      run: python PriceTracker/main_price_tracker.py
