name: Price Tracker

on:
  schedule:
    - cron: '0 */3 * * *'  # Schedule the job to run every 3 hours
  workflow_dispatch:  # Allows manual triggering

env:
  PYTHON_VERSION: 3.9  # Define the Python version as an environment variable

jobs:
  track_prices:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip  # Cache location
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}  # Cache key based on OS and requirements hash
        restore-keys: |
          ${{ runner.os }}-pip-  # Fallback key if exact match is not found

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Run the script
      run: python PriceTracker/main_price_tracker.py
