name: Stock Price Forecast

on:
  schedule:
    - cron: '0 06 * * *'  # Schedule the job to run once a day at 06 AM (UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  track_prices:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install requests oauth2client scikit-learn pandas numpy logging yfinance prophet statsmodels json seaborn pygsheets google-auth-oauthlib google-auth-httplib2

    - name: Run the script
      run: python Deploy_Forecast_stock_prices.py
